# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92cded7e03feee67a77cd5e8d1e27d91623793f32af77a74d2721546a883d3cd029e70f09f49e6edf1e9b6d3168d4689c8821491d7775d7deca2ceacb7f5277a

test:
  secret_key_base: 7988576eb1be6107e2f8c33c3e90ab04949ce424a68baa1698c3bf49a9f7fcb07dd52f80d153c72ce955db319d1d298769f9f5d166139ed56269a084522622b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
