# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# [poke, aoe, pick, protect, push]

  Champion.create({name: "Akali", role: "pick"}) 
  Champion.create({name: "Alistar", role: "protect;aoe"}) 
  Champion.create({name: "Amumu", role: "aoe"}) 
  Champion.create({name: "Anivia", role: "aoe"}) 
  Champion.create({name: "Annie", role: "pick"}) 
  Champion.create({name: "Ashe", role: "pick"}) 
  Champion.create({name: 'Aatrox', role: 'poke;engage'})
  Champion.create({name: "Blitzcrank", role: " "}) 
  Champion.create({name: "Brand", role: "poke;aoe"}) 
  Champion.create({name: "Caitlyn", role: "poke;push;protect"}) 
  Champion.create({name: "Cassiopeia", role: "poke;aoe"}) 
  Champion.create({name: "Cho'Gath", role: "protect;push"}) 
  Champion.create({name: "Corki", role: "poke"}) 
  Champion.create({name: "Darius", role: "pick"}) 
  Champion.create({name: "Dr. Mundo", role: "poke;push"}) 
  Champion.create({name: "Diana", role: "aoe;pick"}) 
  Champion.create({name: "Draven", role: "protect"}) 
  Champion.create({name: "Evelynn", role: "pick;aoe"}) 
  Champion.create({name: "Ezreal", role: "poke"}) 
  Champion.create({name: "Fiddlesticks", role: "aoe"}) 
  Champion.create({name: "Fiora", role: "push"}) 
  Champion.create({name: "Fizz", role: "pick"}) 
  Champion.create({name: "Galio", role: "aoe;protect"}) 
  Champion.create({name: "Gangplank", role: "push"}) 
  Champion.create({name: "Garen", role: "push"}) 
  Champion.create({name: "Gragas", role: "poke;aoe"}) 
  Champion.create({name: "Graves", role: "push"}) 
  Champion.create({name: "Hecarim", role: "aoe"}) 
  Champion.create({name: "Heimerdinger", role: "push;poke"}) 
  Champion.create({name: "Irelia", role: "push"}) 
  Champion.create({name: "Janna", role: "protect"}) 
  Champion.create({name: "Jarvan IV", role: "protect"}) 
  Champion.create({name: "Jax", role: "push"}) 
  Champion.create({name: "Jayce", role: "poke"}) 
  Champion.create({name: "Karma", role: "protect"}) 
  Champion.create({name: "Karthus", role: "poke;aoe"}) 
  Champion.create({name: "Kassadin", role: "pick"}) 
  Champion.create({name: "Katarina", role: "aoe"}) 
  Champion.create({name: "Kayle", role: "protect;push"}) 
  Champion.create({name: "Kennen", role: "aoe"}) 
  Champion.create({name: "Kog'Maw", role: "poke;protect"}) 
  Champion.create({name: "LeBlanc", role: "pick"}) 
  Champion.create({name: "Lee Sin", role: "protect;pick"}) 
  Champion.create({name: "Leona", role: "aoe;protect"}) 
  Champion.create({name: "Lulu", role: "protect"}) 
  Champion.create({name: "Lux", role: "poke;protect"}) 
  Champion.create({name: "Malphite", role: "aoe"}) 
  Champion.create({name: "Malzahar", role: "pick;aoe"}) 
  Champion.create({name: "Maokai", role: "push;aoe"}) 
  Champion.create({name: "Master Yi", role: "push"}) 
  Champion.create({name: "Miss Fortune", role: "aoe"}) 
  Champion.create({name: "Mordekaiser", role: "pick"}) 
  Champion.create({name: "Morgana", role: "protect"}) 
  Champion.create({name: "Nasus", role: "push"}) 
  Champion.create({name: "Nautilus", role: "protect;aoe"}) 
  Champion.create({name: "Nidalee", role: "poke"}) 
  Champion.create({name: "Nocturne", role: "pick"}) 
  Champion.create({name: "Nunu", role: "poke;aoe"}) 
  Champion.create({name: "Olaf", role: "poke;push"}) 
  Champion.create({name: "Orianna", role: "aoe"}) 
  Champion.create({name: "Pantheon", role: "push"}) 
  Champion.create({name: "Poppy", role: "pick"}) 
  Champion.create({name: "Rammus", role: "protect;aoe"}) 
  Champion.create({name: "Renekton", role: "push"}) 
  Champion.create({name: "Rengar", role: "pick;push"}) 
  Champion.create({name: "Riven", role: "push"}) 
  Champion.create({name: "Rumble", role: "aoe;poke"}) 
  Champion.create({name: "Ryze", role: "aoe"}) 
  Champion.create({name: "Sejuani", role: "aoe"}) 
  Champion.create({name: "Shaco", role: "push;pick"}) 
  Champion.create({name: "Shen", role: "protect;push"}) 
  Champion.create({name: "Shyvana", role: "push"}) 
  Champion.create({name: "Singed", role: "push"}) 
  Champion.create({name: "Sion", role: "push"}) 
  Champion.create({name: "Sivir", role: "push"}) 
  Champion.create({name: "Skarner", role: "pick"}) 
  Champion.create({name: "Sona", role: "protect;poke"}) 
  Champion.create({name: "Soraka", role: "protect"}) 
  Champion.create({name: "Swain", role: "aoe"}) 
  Champion.create({name: "Syndra", role: "pick;aoe"}) 
  Champion.create({name: "Talon", role: "pick"}) 
  Champion.create({name: "Taric", role: "protect;"}) 
  Champion.create({name: "Teemo", role: "push;"}) 
  Champion.create({name: "Tristana", role: "protect;poke"}) 
  Champion.create({name: "Trundle", role: "poke;protect"}) 
  Champion.create({name: "Tryndamere", role: "push"}) 
  Champion.create({name: "Twisted Fate", role: "poke;pick"}) 
  Champion.create({name: "Twitch", role: "protect"}) 
  Champion.create({name: "Udyr", role: "protect;push"}) 
  Champion.create({name: "Urgot", role: "poke"}) 
  Champion.create({name: "Varus", role: "poke"}) 
  Champion.create({name: "Vayne", role: "protect"}) 
  Champion.create({name: "Veigar", role: "aoe;pick"}) 
  Champion.create({name: "Viktor", role: "aoe"}) 
  Champion.create({name: "Vladimir", role: "aoe"}) 
  Champion.create({name: "Volibear", role: "protect"}) 
  Champion.create({name: "Warwick", role: "pick"}) 
  Champion.create({name: "Wukong", role: "aoe;push"}) 
  Champion.create({name: "Xerath", role: "aoe;poke"}) 
  Champion.create({name: "Xin Zhao", role: "push;pick"}) 
  Champion.create({name: "Yorick", role: "poke;push"}) 
  Champion.create({name: "Ziggs", role: "poke;aoe"}) 
  Champion.create({name: "Zilean", role: "protect"}) 
  Champion.create({name: "Zyra", role: "protect;aoe"}) 
