# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# [poke, aoe, pick, protect, push]

a = Video.create({title: 'Faker vs. Ryu', youtube_id: 'ZPCfoCVCx3U'})
a.champion_list.add(["zed"], parse: true)
a.player_list.add(["faker","ryu"], parse: true)
a.team_list.add(["SKT T1"], parse: true)
a.save

b = Video.create({title: "Froggen's Yasuo", youtube_id: 'ygU6FhJ-1GA'})
b.champion_list.add(["yasuo"], parse: true)
b.player_list.add(["froggen"], parse: true)
b.save

c = Video.create({title: "Diamond 1 AP Kog'Maw", youtube_id: '5Q1sJI1eIUI'})
c.champion_list.add(["kog'maw"], parse:true)
c.save

d = Video.create({title: "Faker Yasuo", youtube_id: "mSoabkqFCnY"})
d.champion_list.add(["yasuo"], parse: true)
d.player_list.add(["faker"], parse: true)
d.save

e = Video.create({title: "Froggen Anivia vs Katarina", youtube_id: "dNJSpkLe3UY"})
e.champion_list.add(["anivia", "katarina"], parse: true)
e.player_list.add(["froggen"], parse: true)
e.save

f = Video.create({title: "Doublelift Vayne vs Hai Lulu", youtube_id: "0uVIc-V-7gk"})
f.champion_list.add(["vayne", "lulu"], parse: true)
f.player_list.add(["hai", "doublelift"], parse: true)
f.team_list.add(["CLG","C9"], parse: true)
f.save

g = Streamer.create({twitch_handle: "tsm_wildturtle"})
g.aliases << Alias.create({name: "wildturtle"})
g.aliases << Alias.create({name: "lolcat4"})
g.save

h = Streamer.create({twitch_handle: "imaqtpie"})
h.aliases << Alias.create({name: "imaqtpie"})
h.aliases << Alias.create({name: "sqwaak"})
h.save

i = Streamer.create({twitch_handle: "phantoml0rd"})
i.aliases << Alias.create({name: "phantoml0rd"})
i.save

j = Streamer.create({twitch_handle: "mushisgosu"})
j.aliases << Alias.create({name: "clgdeftsu"})
j.save

k = Streamer.create({twitch_handle: "tsm_dyrus"})
k.aliases << Alias.create({name: "ultrabaymax76000"})
k.aliases << Alias.create({name: "1800microwaves"})
k.aliases << Alias.create({name: "dyrus"})
k.save

l = Streamer.create({twitch_handle: "tsm_bjergsen"})
l.aliases << Alias.create({name: "roadtochallenger"})
l.aliases << Alias.create({name: "bjergsen"})
l.save

m = Streamer.create({twitch_handle: "scarra"})
m.aliases << Alias.create({name: "scarra"})
m.save

n = Streamer.create({twitch_handle: "clgdoublelift"})
n.aliases << Alias.create({name: "doublelift"})
n.aliases << Alias.create({name: "pengyiliang"})
n.save

o = Streamer.create({twitch_handle: "curse_piglet"})
o.aliases << Alias.create({name: "crspiglet"})
o.save

Champion.create({name: "Aatrox", role: "push"})
Champion.create({name: "Ahri", role: "pick"})
Champion.create({name: "Akali", role: "pick"})
Champion.create({name: "Alistar", role: "protect;aoe"})
Champion.create({name: "Amumu", role: "aoe"})
Champion.create({name: "Anivia", role: "aoe"})
Champion.create({name: "Annie", role: "aoe;pick"})
Champion.create({name: "Ashe", role: "pick;poke"})
Champion.create({name: "Azir", role: "push"})
Champion.create({name: "Blitzcrank", role: "pick"})
Champion.create({name: "Brand", role: "poke;aoe"})
Champion.create({name: "Braum", role: "protect"})
Champion.create({name: "Caitlyn", role: "push;poke"})
Champion.create({name: "Cassiopeia", role: "aoe;poke"})
Champion.create({name: "Cho'Gath", role: "poke;aoe"})
Champion.create({name: "Corki", role: "poke"})
Champion.create({name: "Darius", role: "push"})
Champion.create({name: "Diana", role: "aoe;pick"})
Champion.create({name: "Dr. Mundo", role: "poke;push"})
Champion.create({name: "Draven", role: "protect"})
Champion.create({name: "Elise", role: "poke"})
Champion.create({name: "Evelynn", role: "pick;aoe"})
Champion.create({name: "Ezreal", role: "poke"})
Champion.create({name: "Fiddlesticks", role: "aoe"})
Champion.create({name: "Fiora", role: "push;aoe"})
Champion.create({name: "Fizz", role: "pick"})
Champion.create({name: "Galio", role: "protect;aoe"})
Champion.create({name: "Gangplank", role: "push;poke"})
Champion.create({name: "Garen", role: "push;pick"})
Champion.create({name: "Gnar", role: "push;poke"})
Champion.create({name: "Gragas", role: "aoe;poke"})
Champion.create({name: "Graves", role: "aoe"})
Champion.create({name: "Hecarim", role: "aoe;pick"})
Champion.create({name: "Heimerdinger ", role: "aoe;push"})
Champion.create({name: "Irelia", role: "push"})
Champion.create({name: "Janna", role: "protect;poke"})
Champion.create({name: "Jarvan IV", role: "pick"})
Champion.create({name: "Jax", role: "push"})
Champion.create({name: "Jayce", role: "poke"})
Champion.create({name: "Jinx", role: "poke;protect;push"})
Champion.create({name: "Karma", role: "protect;poke"})
Champion.create({name: "Karthus", role: "poke;aoe"})
Champion.create({name: "Kassadin", role: "pick"})
Champion.create({name: "Katarina", role: "aoe"})
Champion.create({name: "Kayle", role: "protect;push"})
Champion.create({name: "Kennen", role: "aoe;poke"})
Champion.create({name: "Kha'Zix", role: "pick"})
Champion.create({name: "Kog'Maw", role: "poke;protect"})
Champion.create({name: "LeBlanc", role: "pick"})
Champion.create({name: "Lee Sin", role: "protect;pick"})
Champion.create({name: "Leona", role: "protect;aoe"})
Champion.create({name: "Lissandra", role: "aoe;poke"})
Champion.create({name: "Lucian", role: "poke;protect"})
Champion.create({name: "Lulu", role: "poke;aoe;protect"})
Champion.create({name: "Lux", role: "poke;aoe"})
Champion.create({name: "Malphite", role: "aoe;protect"})
Champion.create({name: "Malzahar", role: "pick;aoe"})
Champion.create({name: "Maokai", role: "protect;aoe"})
Champion.create({name: "Master Yi", role: "push"})
Champion.create({name: "Miss Fortune", role: "aoe"})
Champion.create({name: "Mordekaiser", role: "push"})
Champion.create({name: "Morgana", role: "protect"})
Champion.create({name: "Nami", role: "aoe;protect;poke"})
Champion.create({name: "Nasus", role: "push"})
Champion.create({name: "Nautilus ", role: "protect;pick"})
Champion.create({name: "Nidalee", role: "protect;poke"})
Champion.create({name: "Nocturne ", role: "pick"})
Champion.create({name: "Nunu", role: "aoe;protect"})
Champion.create({name: "Olaf", role: "poke;push"})
Champion.create({name: "Orianna", role: "aoe"})
Champion.create({name: "Pantheon", role: "pick"})
Champion.create({name: "Poppy", role: "push;pick"})
Champion.create({name: "Quinn", role: "push"})
Champion.create({name: "Rammus", role: "protect;pick"})
Champion.create({name: "Renekton", role: "push"})
Champion.create({name: "Rengar", role: "pick;push"})
Champion.create({name: "Riven", role: "push"})
Champion.create({name: "Rumble", role: "aoe;poke"})
Champion.create({name: "Ryze", role: "protect;aoe"})
Champion.create({name: "Sejuani", role: "aoe"})
Champion.create({name: "Shaco", role: "push;pick"})
Champion.create({name: "Shen", role: "protect;push"})
Champion.create({name: "Shyvana", role: "push"})
Champion.create({name: "Singed", role: "push"})
Champion.create({name: "Sion", role: "push;pick"})
Champion.create({name: "Sivir", role: "protect;push"})
Champion.create({name: "Skarner", role: "pick"})
Champion.create({name: "Sona", role: "poke;aoe;protect"})
Champion.create({name: "Soraka", role: "protect;poke"})
Champion.create({name: "Swain", role: "aoe"})
Champion.create({name: "Syndra", role: "pick"})
Champion.create({name: "Talon", role: "pick"})
Champion.create({name: "Taric", role: "protect"})
Champion.create({name: "Teemo", role: "push"})
Champion.create({name: "Thresh", role: "pick;protect"})
Champion.create({name: "Tristana", role: "poke;protect;push"})
Champion.create({name: "Trundle", role: "poke;push"})
Champion.create({name: "Tryndamere", role: "push"})
Champion.create({name: "Twisted Fate", role: "pick"})
Champion.create({name: "Twitch", role: "protect;pick"})
Champion.create({name: "Udyr", role: "push"})
Champion.create({name: "Urgot", role: "poke"})
Champion.create({name: "Varus", role: "poke"})
Champion.create({name: "Vayne", role: "protect"})
Champion.create({name: "Veigar", role: "pick;aoe"})
Champion.create({name: "Vel'Koz", role: "pick;aoe"})
Champion.create({name: "Vi", role: "pick"})
Champion.create({name: "Viktor", role: "pick;aoe"})
Champion.create({name: "Vladimir", role: "aoe;push"})
Champion.create({name: "Volibear", role: "pick;push"})
Champion.create({name: "Warwick", role: "push"})
Champion.create({name: "Wukong", role: "aoe"})
Champion.create({name: "Xerath", role: "aoe;pick"})
Champion.create({name: "Xin Zhao", role: "push"})
Champion.create({name: "Yasuo", role: "pick;push"})
Champion.create({name: "Yorick", role: "push;protect"})
Champion.create({name: "Zac", role: "aoe;protect"})
Champion.create({name: "Zed", role: "pick;push"})
Champion.create({name: "Ziggs", role: "aoe"})
Champion.create({name: "Zilean", role: "protect"})